[add] #312 keystore jks 존재하는지 확인

diff --git a/.github/workflows/winey-cd.yml b/.github/workflows/winey-cd.yml
--- a/.github/workflows/winey-cd.yml
+++ b/.github/workflows/winey-cd.yml
@@ -15,42 +15,52 @@ jobs:
         runs-on: ubuntu-latest
 
         steps:
-            - name: Checkout
-              uses: actions/checkout@v4
+            -   name: Checkout
+                uses: actions/checkout@v4
 
-            - name: Set up JDK 17
-              uses: actions/setup-java@v3
-              with:
-                  distribution: 'temurin'
-                  java-version: 17
+            -   name: Set up JDK 17
+                uses: actions/setup-java@v3
+                with:
+                    distribution: 'temurin'
+                    java-version: 17
 
-            - name: Generate winey.keystore.jks
-              run: echo '${{ secrets.WINEY_KEYSTORE }}' | base64 -d > ./app/winey.jks
+            -   name: Generate winey.keystore.jks
+                run: echo '${{ secrets.WINEY_KEYSTORE }}' | base64 -d > ./app/winey.jks
 
-            - name: Generate local.properties
-              env:
-                  AUTH_BASE_URL: ${{ secrets.AUTH_BASE_URL }}
-                  KAKAO_NATIVE_KEY: ${{ secrets.KAKAO_NATIVE_KEY }}
-                  AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
-                  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
-                  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
-                  STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
-              run: |
-                  echo auth.base.url=\"$AUTH_BASE_URL\" >> ./local.properties
-                  echo kakao.native.key=\"$KAKAO_NATIVE_KEY\" >> ./local.properties
-                  echo amplitude.api.key=\"$AMPLITUDE_API_KEY\" >> ./local.properties
-                  echo kakaoNativeKey=$KAKAO_NATIVE_KEY >> ./local.properties
-                  echo keyAlias=$KEY_ALIAS >> ./local.properties
-                  echo keyPassword=$KEY_PASSWORD >> ./local.properties
-                  echo storePassword=$STORE_PASSWORD >> ./local.properties
-
-            - name: Create Google Services JSON File
-              env:
-                 GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
-              run: echo $GOOGLE_SERVICES_JSON > ./app/google-services.json
+            -   name: Check if winey.jks exists
+                run: |
+                    if [ -f "./app/winey.jks" ]; then
+                        echo "winey.jks file exists in the app directory."
+                    else
+                        echo "Error: winey.jks file is missing in the app directory." >&2
+                      exit 1
+                    fi
 
 
-        # PR 제목에서 release v*.*.* 형식의 버전을 추출
+            -   name: Generate local.properties
+                env:
+                    AUTH_BASE_URL: ${{ secrets.AUTH_BASE_URL }}
+                    KAKAO_NATIVE_KEY: ${{ secrets.KAKAO_NATIVE_KEY }}
+                    AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
+                    KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
+                    KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
+                    STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
+                run: |
+                    echo auth.base.url=\"$AUTH_BASE_URL\" >> ./local.properties
+                    echo kakao.native.key=\"$KAKAO_NATIVE_KEY\" >> ./local.properties
+                    echo amplitude.api.key=\"$AMPLITUDE_API_KEY\" >> ./local.properties
+                    echo kakaoNativeKey=$KAKAO_NATIVE_KEY >> ./local.properties
+                    echo keyAlias=$KEY_ALIAS >> ./local.properties
+                    echo keyPassword=$KEY_PASSWORD >> ./local.properties
+                    echo storePassword=$STORE_PASSWORD >> ./local.properties
+
+            -   name: Create Google Services JSON File
+                env:
+                    GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
+                run: echo $GOOGLE_SERVICES_JSON > ./app/google-services.json
+
+
+            # PR 제목에서 release v*.*.* 형식의 버전을 추출
             -   name: Extract Version Name
                 run: echo "##[set-output name=version;]v$(echo '${{ github.event.pull_request.title }}' | grep -oP 'release v\K[0-9]+\.[0-9]+\.[0-9]+')"
                 id: extract_version
